create database "ExchangeDb";
    
create table "ExchangeLog"
(
    "Id"                 integer generated by default as identity primary key,
    "CreatedAt"          timestamp with time zone not null,
    "CreatedBy"          integer                  not null,
    "RecordStatus"       char                     not null,
    "ModifiedAt"         timestamp with time zone,
    "ModifiedBy"         integer,
    "SourceCurrencyCode" varchar(5)               not null,
    "TargetCurrencyCode" varchar(5)               not null,
    "SourceAmount"       decimal(10, 2)           not null,
    "TargetAmount"       decimal(10, 2)           not null,
    "Direction"          smallint                 not null,
    "RateDate"           timestamp with time zone
)

alter table "ExchangeLog"
    owner to appuser;

create index "IX_ExchangeLog_CreatedBy" on "ExchangeLog" ("CreatedBy");
create index "IX_ExchangeLog_SourceCurrencyCode" on "ExchangeLog" ("SourceCurrencyCode");
create index "IX_ExchangeLog_TargetCurrencyCode" on "ExchangeLog" ("TargetCurrencyCode");